### ISSUE TITLE
Binary file handling

### ISSUE THREAD

**Issue by naoak** [remcovaes/web-test-runner-vite-plugin#1]
First of all, thank you for the great plugin. It is really helpful.

When loading a binary file, the response was wrong (content length was larger than expected) and could not be loaded correctly. There seems to be a problem with the handling of binary files in the proxy.

I have found that a small modification to the proxy part solves the problem, so may I send a Pull Request?

**Comment by remcovaes** [comment]
Sure, go ahead!

**Comment by naoak** [comment]
@remcovaes
I've made it. Please take a look! #2
