### ISSUE TITLE
wtr message about rollup entry points

### ISSUE THREAD

**Issue by peschee** [remcovaes/web-test-runner-vite-plugin#7]
My tests run fine. However, I'm seeing the following output before tests are run:

`(!) Could not auto-determine entry point from rollupOptions or html files and there are no explicit optimizeDeps.include patterns. Skipping dependency pre-bundling.`

**Comment by remcovaes** [comment]
I am afraid this is not enough information for me to help you. Could you provide a reproduction recipe, so I can get the same error on my machine?

**Comment by peschee** [comment]
I'm using a pretty standard storybook + vite (builder) + lit setup. My vite config is basically empty:

```ts
import { defineConfig } from 'vite';

export default defineConfig({});
```

My test runner config is more or less:

```js
import { playwrightLauncher } from '@web/test-runner-playwright';
import { vitePlugin } from '@remcovaes/web-test-runner-vite-plugin';

/**
 * Filter unwanted browser log statements we're not really interested in when running tests.
 *
 * @type {import('@web/test-runner').TestRunnerConfig.filterBrowserLogs}
 * @param args
 * @returns {boolean}
 */
const removeUnneededLogs = ({ args }) => {
  const ignoredBrowserLogs = new Set(['Lit is in dev mode. Not recommended for production! See https://lit.dev/msg/dev-mode for more information.']);

  return !args.some(argument => ignoredBrowserLogs.has(argument));
};

/**
 * @type {import('@web/test-runner').TestRunnerConfig}
 */
const config = {
  files: ['**/*.{test,spec}.ts', '!**/node_modules/**/*'],
  plugins: [vitePlugin()],
  nodeResolve: true,
  browsers: [playwrightLauncher({ product: 'chromium' })]
};

export default config;
```

I see this message before Chromium is being launched. I'll try to get a repro together later today.
